services:
  django:
    image: prjdja:0.2
    build:
      context: ./config/django-image
    volumes:
      - ./src/django:/usr/src/app:delegated
    environment:
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_NAME: ${DATABASE_NAME}
      DJANGO_SU_NAME: ${DJANGO_SU_NAME}
      DJANGO_SU_PASSWORD: ${DJANGO_SU_PASSWORD}
      DJANGO_SU_EMAIL: ${DJANGO_SU_EMAIL}
    ports:
      - 8000:8000
    networks:
      red:

  postgres:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    command: postgres -c 'max_connections=600'
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./data/dbdata:/var/lib/postgresql/data:delegated
    networks:
      red:

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    networks:
      - red

networks:
  red: