# Generated by Django 5.0.7 on 2024-07-13 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('full_name', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('cuil', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator('^\\d{8,11}$', message='El CUIL debe tener entre 8 y 11 dígitos.')])),
                ('domicilio', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator('^\\d{8,12}$', message='El teléfono debe tener entre 8 y 12 dígitos.')])),
            ],
        ),
    ]
