# Generated by Django 5.0.7 on 2024-07-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_rename_full_name_persona_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fotos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persona',
            name='lista',
            field=models.BooleanField(default=False),
        ),
    ]
