# Generated by Django 5.0.7 on 2024-07-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_persona_fotos_persona_lista'),
    ]

    operations = [
        migrations.CreateModel(
            name='talleres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=130)),
            ],
        ),
    ]
