# Generated by Django 5.0.7 on 2024-07-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_persona_tall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.CharField(),
        ),
    ]
